language: python
env:
  global:
    - COVERAGE_CMD="coverage run -m"
    - COVERAGE_DEP="coverage"
matrix:
  include:
  - python: "2.7"
    services:
    - docker
    env: TOX_ARGS="-e py27-install-extensions,py27-disable-extensions,py27-without-extensions"
  - python: "3.4"
    services:
    - docker
    env: TOX_ARGS="-e py34-install-extensions,py34-disable-extensions,py34-without-extensions"
  - python: "3.4"
    services:
    - docker
    arch: arm64
    env: TOX_ARGS="-e py34-install-extensions,py34-disable-extensions,py34-without-extensions"
  - python: "3.5"
    services:
    - docker
    env: TOX_ARGS="-e py35-install-extensions,py35-disable-extensions,py35-without-extensions"
  - python: "3.5"
    services:
    - docker
    arch: arm64
    env: TOX_ARGS="-e py35-install-extensions,py35-disable-extensions,py35-without-extensions"
  - python: "3.6"
    services:
    - docker
    env: TOX_ARGS="-e py36-install-extensions,py36-disable-extensions,py36-without-extensions"
  - python: "3.6"
    services:
    - docker
    arch: arm64
    env: TOX_ARGS="-e py36-install-extensions,py36-disable-extensions,py36-without-extensions"
  - python: "3.7"
    services:
    - docker
    dist: xenial
    sudo: true
    env: TOX_ARGS="-e py37-install-extensions,py37-disable-extensions,py37-without-extensions"
  - python: "3.7"
    services:
    - docker
    arch: arm64
    dist: xenial
    sudo: true
    env: TOX_ARGS="-e py37-install-extensions,py37-disable-extensions,py37-without-extensions"
  - python: "pypy3"
    env: TOX_ARGS="-e pypy-without-extensions"
install:
  - pip install tox coveralls wheel cibuildwheel
script:
  - tox $TOX_ARGS
  - cibuildwheel --output-dir dist
after_script:
  - coverage combine
  - coveralls
